export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const SEARCH_GUEST = 'SEARCH_GUEST';
export const CLEAR_SEARCH_GUEST = 'CLEAR_SEARCH_GUEST';
export const REMOVE_USER = 'REMOVE_USER';
export const EDIT_USER = 'EDIT_USER';
